# Generated by Django 3.1.6 on 2021-03-02 18:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_num', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('case_type', models.CharField(choices=[('Support', 'Support'), ('Training', 'Training'), ('Maintenance', 'Maintenance'), ('installation', 'Installation')], max_length=100)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], max_length=100)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_date', models.DateTimeField()),
                ('actual_date', models.DateTimeField()),
                ('machine_down', models.BooleanField(default=False)),
                ('customer_contact', models.CharField(max_length=100)),
                ('case_description', models.TextField()),
                ('on_hold', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equip_sn', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('equip_pn', models.CharField(max_length=100)),
                ('equip_description', models.TextField()),
                ('installation_date', models.DateTimeField()),
                ('warranty', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('part_pn', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('part_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_num', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_contact', models.CharField(max_length=100)),
                ('remote', models.BooleanField(default=False)),
                ('visit_start', models.TimeField()),
                ('visit_end', models.TimeField()),
                ('visit_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('travel_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('num_of_engineers', models.IntegerField()),
                ('visit_summary', models.TextField()),
                ('case_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASISupport_app.case')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASISupport_app.customer')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASISupport_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='VisitParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_pn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASISupport_app.parts')),
                ('visit_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASISupport_app.visit')),
            ],
        ),
        migrations.CreateModel(
            name='CaseEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASISupport_app.case')),
                ('equip_sn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASISupport_app.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='case_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASISupport_app.employee'),
        ),
        migrations.AddField(
            model_name='case',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASISupport_app.customer'),
        ),
    ]
