# Generated by Django 3.1.6 on 2021-03-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASISupport_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='actual_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
