# Generated by Django 3.1.6 on 2021-03-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASISupport_app', '0003_auto_20210302_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='actual_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
