# Generated by Django 3.1.6 on 2021-03-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASISupport_app', '0006_auto_20210304_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='actual_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='target_date',
            field=models.DateField(),
        ),
    ]
