# Generated by Django 3.1.6 on 2021-03-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASISupport_app', '0007_auto_20210304_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='visit_hours',
        ),
        migrations.AddField(
            model_name='visitparts',
            name='charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitparts',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
