# Generated by Django 3.1.6 on 2021-03-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASISupport_app', '0008_auto_20210309_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='num_of_engineers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
