# Generated by Django 3.1.6 on 2021-03-30 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ASISupport_app', '0009_auto_20210309_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='cancellation_reason',
        ),
    ]
