# Generated by Django 3.1.6 on 2021-03-30 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ASISupport_app', '0010_remove_case_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
