# Generated by Django 3.1.6 on 2021-04-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASISupport_app', '0011_visit_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='on_hold_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
