# Generated by Django 3.1.6 on 2021-05-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ASISupport_app', '0013_auto_20210428_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone_number',
        ),
    ]
